name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t madworks
    - name: tagging the image
      run: docker tag madworks matheeshworks/madworks:latest
    - name: login to docker
      run: docker login -u matheeshworks -p "${{secrets.DOCKERTOKEN}}"
    - name: push the image to docker hub
      run: docker push matheeshworks/madworks:latest
