name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t madworks
           docker tag madworks matheeshworks/madworks:latest
           docker login -u matheeshworks -p "${{secrets.DOCKERTOKEN}}"
           docker push matheeshworks/madworks:latest
